---

version: "2.1"
services:
  #
  # Nginx proxy
  #
  nginx:
    image: linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ./config/nginx/proxy.conf:/config/nginx/proxy.conf
      - ./config/nginx/ssl.conf:/config/nginx/ssl.conf
      - ./config/nginx/site-confs:/config/nginx/site-confs
        #- ./config/nginx/site-confs/transmission.subdomain.conf:/config/nginx/site-confs/transmission.subdomain.conf
        #- ./config/nginx/site-confs/jackett.subdomain.conf:/config/nginx/site-confs/jackett.subdomain.conf
        #- ./config/nginx/site-confs/default:/config/nginx/site-confs/default
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  #
  # Transmission
  #
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $MEDIA_DIR/transmission:/config
      - ./config/transmission/settings.json:/config/settings.json
      - $MEDIA_DIR:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  #
  # miniDLNA server
  #
  minidlna:
    image: vladgh/minidlna
    container_name: minidlna
    environment:
      - MINIDLNA_MEDIA_DIR_1=V,/media/movies
      - MINIDLNA_MEDIA_DIR_2=V,/media/tvshows
      - MINIDLNA_MEDIA_DIR_3=V,/media/cartoons
      - MINIDLNA_friendly_name=raspberry
      - MINIDLNA_root_container=V
      - MINIDLNA_inotify=yes
    volumes:
      - $MEDIA_DIR:/media
    network_mode: host
    restart: unless-stopped

  #
  # Jackett + Sonarr + Radarr
  #
  tor:
    image: dperson/torproxy
    container_name: tor
    environment:
      - USERID=$PUID
      - GROUPID=$PGID
      - TZ=$TZ
      - BW=100
      - LOCATION=UA
    ports:
      - 8118:8118
      - 9050:9050
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - RUN_OPTS=--ProxyConnection=tor:8118
    volumes:
      - $MEDIA_DIR/jackett:/config
      #- ./data/jackett:/config
      - $MEDIA_DIR/movies:/downloads
    ports:
      - 9117:9117
    #depends_on:
    #  tor:
    #    condition: service_healthy
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $MEDIA_DIR/sonarr:/config
      - $MEDIA_DIR/tvshows:/tv
      - $MEDIA_DIR/movies:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $MEDIA_DIR/radarr:/config
      - $MEDIA_DIR/movies:/movies
      - $MEDIA_DIR/movies:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
